### ISSUE TITLE
[Q] matching image tag patterns

### ISSUE THREAD

**Issue by timoweiss** [rancher/webhook-service#55]
Hey folks, thanks for this neat service! I'm currently playing around with the upgrade feature and was wondering if it is possible to match not only exact tags, but also against a certain pattern, eg:

matcher: `release-*`
dockerhub tag: `release-v1.1.2`

Many thanks in advance!

**Comment by deniseschannon** [comment]
No, at this time, it's only exact tags, but I've created this issue in Rancher as an enhancement request:

https://github.com/rancher/rancher/issues/8446
