### ISSUE TITLE
serviceUpgrade: support docker registry notifications

### ISSUE THREAD

**Issue by mnzaki** [rancher/webhook-service#56]
The `serviceUpgrade` driver currently supports Docker Hub webhooks. It would be immensely useful to also support notification events from the docker registry, for people hosting their own private registries.

Example payloads: https://docs.docker.com/registry/notifications/#envelope

**Comment by deniseschannon** [comment]
I've made an enhancement in our main repo: https://github.com/rancher/rancher/issues/8445

We'll be closing issues in this repo.
